name = "lao-waitlist"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./dist"

[vars]
PUBLIC_SITE_URL = "https://lao.lt"
WAITLIST_FROM_EMAIL = "LAO <waitlist@lao.lt>"

[[d1_databases]]
binding = "WAITLIST_DB"
database_name = "lao-waitlist"
database_id = "5b360aaf-6939-4c9b-bc5a-8b522de4c408"
